issues:
  exclude-files:
    - ".*_test\\.go$"

linters-settings:
  gci:
    custom-order: true
    sections:
      - standard
      - prefix(azugo.io/azugo)
      - default

linters:
  presets:
    - comment
    - format
    - bugs
    - performance
    - unused
    - test
    - sql
    - style

  enable:
    - wsl

  disable:
    - godox
    - tagalign
    - exhaustruct
    - depguard
    - wrapcheck
    - gochecknoinits
    - varnamelen
    - funlen
    - ireturn
    - mnd
    - interfacebloat
    - gochecknoglobals
    - err113
    - lll
    - nilnil
    - containedctx
    - gomoddirectives
    - nolintlint
    - goconst
