when:
  branch:
    - main
  event:
    - push

steps:
  - name: test
    image: golang:1.22
    pull: true
    environment:
      - CGO_ENABLED=1
    commands:
      - go test -cover -race -coverprofile=coverage.out -covermode=atomic -json ./... > report.json
