when:
  branch:
    - main
  event:
    - push
    - pull_request

steps:
  - name: vendor
    image: golang:1.24-alpine
    commands:
      - go mod vendor

  - name: golangci-lint
    image: golangci/golangci-lint:v1.61-alpine
    pull: true
    depends_on:
      - vendor
    commands:
      - golangci-lint run --timeout 3m --out-format=checkstyle:golangci-lint.out,colored-line-number
    when:
      branch: main
      event: push

  - name: review-go
    image: woodpeckerci/plugin-reviewdog-golangci-lint:1.61
    pull: true
    depends_on:
      - vendor
    settings:
      token:
        from_secret: reviewdog_token
    when:
      event: pull_request
