when:
  branch:
    - main
  event:
    - pull_request

steps:
  - name: golangci-lint
    image: golangci/golangci-lint:v1.57-alpine
    pull: true
    commands:
      - golangci-lint run --timeout 3m --out-format=checkstyle:golangci-lint.out,colored-line-number
