when:
  branch:
    - main
  event:
    - pull_request

matrix:
  GO_VERSION:
    - 1.23
    - 1.24

steps:
  - name: test
    image: golang:${GO_VERSION}-alpine
    pull: true
    environment:
      CGO_ENABLED: 0
    commands:
      - go test -v ./...
