when:
  branch:
    - main
  event:
    - pull_request

matrix:
  GO_VERSION:
    - 1.19
    - 1.20

pipeline:
  - name: test
    image: golang:${GO_VERSION}
    pull: true
    environment:
      - CGO_ENABLED=1
    commands:
      - go test -race ./...
